### PR TITLE
Issue #75-Make the LOGIN page functional

### PR DESCRIPTION
**Pull request by Shounmay**
https://github.com/SurajPratap10/Imagine_AI/assets/90774417/ec1a7094-23f2-41d8-897c-bbbd88c4eeb0

<h3> The above video is demo of Login  and signup functionality. Video starts from 0.03s, sorry for that. Here I have made a Db on Mongo and the URl for that is exposed in .env file. </h3>
<h2> Functionalities </h2>
<li>User can sign-up(register) in the website. Name should be 5 char long, should be a valid email and password must be minimum 8 char long with atleast 1 uppercase,1 lowercase,1 digit</li>
<li> In signup case all these checks are done in backend-server</li>
<li>In signup and login, user can't submit without filling the inputs.</li>
</li>For any kind of error, user will get an error toast notification at the bottom</li>
<li>In case of success in signup/login the user will be redirected to homepage(index.html). This redirection is slow due to absence of optimized reconciliation algorithms(like reactjs uses it) </li>
<h2> Security Issues and Further Enhancements </h2>
<li> If merged, then the .env file can expose the DB URI. So just remove the part of URI after merging and paste it in deployed server environment variable</li>
<li> frontend enhancement for showing password can be done </li>
<li>feature  enhancement for confirm password feature in signup can be done </li>

### CODE REVIEW

**Comment by Shounmay** [comment]
Hey @SurajPratap10 please review it

**Comment by SurajPratap10** [comment]
image


@Shounmay

**Comment by Shounmay** [comment]
Please review it @SurajPratap10 . The issue was caused due to conflicts.

**Review by SurajPratap10 — APPROVED** [review]
Looks Good 👍

**Comment by SurajPratap10** [comment]
Great Work @Shounmay 🔥

**Comment by Shounmay** [comment]
Hey i can't get that the images in deployed preview are aligned in a proper way, while the images aligned in deployed server are not.
<h1> Deploy Preview of My PR</h1>
deployed_preview_1
<h1>Deployed version in your main branch </h1>
deployed_image

**Pull request merged**
