### PR TITLE
Latest changes made [NAVBAR]

### PR DESCRIPTION
**Pull request by PR1YAM9**
hi @SurajPratap10 I realised what mistake i was making it should work this time.

### CODE REVIEW

**Comment by PR1YAM9** [comment]
Hi @SurajPratap10 , the navbar is working fine in every page and is responsive for every media width please merge this PR under ggsoc

**Comment by PR1YAM9** [comment]
i have resolved the conflicts it is ready to merge

**Comment by SurajPratap10** [comment]
image

**Comment by PR1YAM9** [comment]
@SurajPratap10 how can i fix this ?

**Comment by PR1YAM9** [comment]
> @SurajPratap10 how can i fix this ?

I have reverted the changes made in json file and json lock file

**Comment by PranavSikarwal** [comment]
@PR1YAM9 it says, cannot parse json file i.e. may somewhere you have imported the filecontent and then erroneously parsed it.

**Comment by PR1YAM9** [comment]
> @PR1YAM9 it says, cannot parse json file i.e. may somewhere you have imported the filecontent and then erroneously parsed it.

I have reverted the changes , i added on both the files , actually i added start and express to run the web page 
Will it be solved now or do i have to do something else ?

**Comment by PranavSikarwal** [comment]
@PR1YAM9 no need to hurry you can check every think on personal deployment server, then make a PR other wise it will always give some error, Local checking are many times different than deployment checking. 
You might not see a error on locally but on deployment that error might occur.
We can discuss it in Discuss section of the project as it will spam this pr.

**Comment by SurajPratap10** [comment]
Remember to be updated with the features of the latest website before asking for merge @PR1YAM9

**Comment by PR1YAM9** [comment]
> Remember to be updated with the features of the latest website before asking for merge @PR1YAM9

okay will keep in mind

**Comment by PR1YAM9** [comment]
@SurajPratap10 can you try merging this and check if it's fine?

**Comment by PR1YAM9** [comment]
dont merge rn i will check tmrw as the latest merge relating to navbar is breaking it

**Pull request closed without merging**
