### PR TITLE
Adding Surprise Me button

### PR DESCRIPTION
**Pull request by rutujp78**
Implementing feature #7

https://github.com/SurajPratap10/Imagine_AI/assets/76244494/33698f50-292e-4c3c-ac27-35117c140399

The "Surprise Me!" button chooses random prompt for the user.

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Very nice @rutujp78  just reduce the gap between the `Generate` and `Surprise Me` for the mobile

Screenshot_2023-05-20-19-31-05-096_com android chrome

**Comment by rutujp78** [comment]
Fixed the gap issue for mobile devices.
Screenshot (148)

**Comment by SurajPratap10** [comment]
> Fixed the gap issue for mobile devices. Screenshot (148)

GG 🔥

**Comment by SurajPratap10** [comment]
@rutujp78 I can't find any autogenerated prompts while clicking the `button`..

**Comment by rutujp78** [comment]
> @rutujp78 I can't find any autogenerated prompts while clicking the `button`..

Getting this error : Uncaught ReferenceError: require is not defined
    at main.js:1:1

Instead of "var _constants = require("./constants.js");" -> "import { surpriseMePrompts } from './constants.js';"

**Comment by SurajPratap10** [comment]
> > @rutujp78 I can't find any autogenerated prompts while clicking the `button`..
> 
> Getting this error : Uncaught ReferenceError: require is not defined at main.js:1:1
> 
> Instead of "var _constants = require("./constants.js");" -> "import { surpriseMePrompts } from './constants.js';"

In the video u shared it was running no, so check if u have made any mistake while pushing the code or something.

**Comment by SurajPratap10** [comment]
also there are conflicted to resolve @rutujp78

**Comment by SurajPratap10** [comment]
Now it's working fine @rutujp78  but please change the `button` design and other stuff it according to the current website as it has been updated via the PRs of other folks. 

image

**Comment by SurajPratap10** [comment]
And also resolve the conflicts your PR is creating @rutujp78 

image

**Pull request closed without merging**
