### PR TITLE
Add Chatbot Functionality to IMAGINE - AI

### PR DESCRIPTION
**Pull request by amanver45**
#1305

Add Chatbot Functionality to IMAGINE - AI

## Fixes #(issue_no)

#1305 

## Screenshots

|

https://github.com/user-attachments/assets/61cfdcad-5d2d-4677-8fb3-f984e7e9bf0d

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by amanver45** [comment]
@SurajPratap10 pls merge this pr

**Comment by MastanSayyad** [comment]
@SurajPratap10 Please review this PR

**Comment by amanver45** [comment]
@SurajPratap10 pls check this

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Pull request merged**
