### PR TITLE
Fixes Navbar

### LINKED ISSUE #364: [style]: Navbar is breaking
### What's the style idea?

We need to improve  navigation bar of the website.
I aant to work on this under gssoc'23

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Isha988**
# Description
Improved navbar and made it responsive

## Fixes #(issue_no)
closes #364

### CODE REVIEW

**Comment by Isha988** [comment]
@SurajPratap10 have a look at the changes made.
Let me know, If any further improvement is required.

**Comment by Isha988** [comment]
@SurajPratap10 I have updated this branch and also resolved the conflicts.

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve the conflicts @Isha988

**Comment by Isha988** [comment]
> Resolve the conflicts @Isha988

Done 👍

**Comment by Isha988** [comment]
@SurajPratap10 resolved.

**Review by SurajPratap10 — APPROVED** [review]

**Comment by Isha988** [comment]
> Ok , after deployment it's breaking image

I will fix it and I don't need any points for that.
Even I am ready to fix it in this pr if you revert the merge.

**Pull request merged**
