### PR TITLE
🚀 Enhance Security and Development Experience: Add .env.example, Remove .env, and Provide Vercel Setup Instructions

### LINKED ISSUE #738: Improve Security: Add .env to .gitignore and Create .env.example for Local Development
**Is your feature request related to a problem? Please describe.**
Currently, sensitive environment variables stored in the .env file are being pushed to the repository, posing a security risk. We should take measures to enhance security by ignoring the .env file from version control and providing a sample .env.example file for local development. This will prevent sensitive information from being exposed and help new developers set up the project environment more easily.

**Proposed Solution:**

1. **Add `.env` to `.gitignore`:**
   Update the `.gitignore` file to include the `.env` file so that it's automatically excluded from version control. This will prevent the sensitive environment variables from being pushed to the repository.

   - Update `.gitignore`:
     ```
     # Ignore .env file
     .env
     ```

2. **Create `.env.example`:**
   Create a `.env.example` file that contains placeholders for the required environment variables along with some instructions on how to populate them. This file will serve as a template for developers to set up their local environment.

   - Create `.env.example`:
     ```
     # Example .env file
       PORT=5000
       MONGODB_URI=mongodb+srv://Jazzy49:MyNodeApp@nodeprojects.tsxlcqi.mongodb.net/Imagine? 
       retryWrites=true&w=majority
       OPENAI_API_KEY="get in from OPEN AI"
       JWT_ACCESS_SECRET=ImagineAiAccessSecret
       JWT_REFRESH_TOKEN=ImagineAiRefreshToken
       GOOGLE_CLIENT_ID=829264938526-gklvdpj86hpc8fn0b58u9lc5p56da1jv.apps.googleusercontent.com
       GOOGLE_CLIENT_SECRET=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
       GOOGLE_AUTH_URI=https://imagine-ai-17zf.vercel.app/auth/google/callback





     # Other configurations
     DEBUG=true
     ```

**Benefits:**

- **Enhanced Security:** Prevents sensitive information from being accidentally pushed to the repository, reducing the risk of data breaches.
- **Simplified Onboarding:** New developers will have clear instructions on how to set up their local environment, making the onboarding process smoother.
- **Consistency:** Developers will have a standardized template to work with, ensuring consistent environment variable names and configurations.

**Implementation Steps:**

1. Update `.gitignore` to include `.env`.
2. Create a `.env.example` file in the repository root directory.
3. Populate `.env.example` with placeholder environment variables and instructions.
4. Update the project's documentation to mention the changes and provide guidance on using `.env.example`.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Nishitbaria**
# Description

🎉 Summary:
This pull request aims to improve the security of the project and streamline the onboarding process by introducing changes related to environment variables. It includes the addition of a .env.example file, the removal of the .env file, and step-by-step instructions for setting up environment variables on Vercel

## Fixes #738 

Replace `issue_no` with the issue number which is fixed in this PR

**Changes:**

1. **Added `.env.example` File:**
   - Created the `.env.example` file containing placeholder environment variables and explanations to guide developers.
   - This file will serve as a template for local development environment setup.

2. **Removed `.env` File:**
   - The sensitive `.env` file has been removed to prevent accidental exposure of sensitive information in the repository.

3. **Provided Vercel Setup Instructions:**
   - Added detailed instructions for maintainers to set up environment variables on Vercel before merging this pull request.
   - These instructions ensure a smooth deployment process while maintaining security and privacy.

🔧 **Instructions for Maintainer:**

Before merging this pull request, please follow these steps on Vercel to set up the environment variables required for the project:

1. Open the Vercel dashboard for the project.
2. Go to the project's settings or environment variables section.
3. Add the necessary environment variables with their corresponding values:
   - `MONGODB_URI`: MongoDB connection string for database access.
   - `OPENAI_API_KEY`: OpenAI API key for integrating with the AI service.
   - `JWT_ACCESS_SECRET`: JWT access token secret for authentication.
   - `JWT_REFRESH_TOKEN`: JWT refresh token secret for authentication.
   - `GOOGLE_CLIENT_ID`: Google OAuth client ID for authentication.
   - `GOOGLE_CLIENT_SECRET`: Google OAuth client secret for authentication.
   - `GOOGLE_AUTH_URI`: Google OAuth authentication URI.
   
4. Ensure the environment variables are securely stored and not exposed publicly.

Once the environment variables are set up on Vercel, you can confidently merge this pull request to enhance project security and development efficiency.

🚀 **Benefits:**

- Improved security by excluding sensitive `.env` file from version control.
- Streamlined onboarding process with clear instructions for local environment setup.
- Enhanced development experience with a standardized environment variable template.

## Screenshots

**Please see this video for vercel settings its imporant**

https://github.com/SurajPratap10/Imagine_AI/assets/85815172/ee380e8e-294a-4a0c-b5bc-7e0d548aafbd

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,**please see video and make changes on vercel if remainning** ,before merging my pull request

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,please see video and make changes on vercel if remainning ,before merging my pull request

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,please review and merge my pull request

**Review by SurajPratap10 — APPROVED** [review]

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,you have given level2 in issue,but in pr you have given level1 ,please value my contribution and give me level2

**Pull request merged**
