### PR TITLE
Added  validation and label in login and sign up page

### LINKED ISSUE #392: No validation and label in login and sign up page
**Describe the bug**
Their is no Validation and label in login and sign up page so user will not be able to know what to add and he can add anything in it 

**To Reproduce**

- do to home page
- click on login button
- you can fill anything in the form and their is no label 

**Expected behavior**
when user come to login page their should be labels in the login page and their should be validation in that so that in email input only email can be added and so on.

**Screenshots**

https://github.com/SurajPratap10/Imagine_AI/assets/119161467/128a8ea4-87cf-4733-81f4-506a38a3dc21

**Desktop (please complete the following information):**
 - OS: All
 - Browser:All
 - Version :All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: ALl
 - Browser : All
 - Version :All

**Additional context**
@SurajPratap10 I am writing to kindly request your attention and consideration in reviewing and accepting issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

### LINKED ISSUE #394: Social Icons link not working in login and sign up page
**Describe the bug**
Social icon links are not working in login and sign up page
**To Reproduce**

- do to home page
- click on login button
- click on social icons
- They are not working

**Expected behavior**
The social icons on clicking should take to respective social handles

**Screenshots**

https://github.com/SurajPratap10/Imagine_AI/assets/119161467/a2f17a67-fc22-4fca-8aa4-30bedb41bca3

**Desktop (please complete the following information):**
 - OS: ALL
 - Browser :All
 - Version:ALl

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser:  All
 - Version: All 

**Additional context**

@SurajPratap10 I am writing to kindly request your attention and consideration in reviewing and accepting issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

### PR DESCRIPTION
**Pull request by lakhan06**
# Description

Added Validation and label in login and sign up page so user will be able to know what to add and he can't  add anything in it

## Screenshots
image
image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by lakhan06** [comment]
@SurajPratap10  I am writing to kindly request your attention and consideration in reviewing and accepting Pull request. I would greatly appreciate it if you could allocate some time to review the Pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by lakhan06** [comment]
@SurajPratap10 pratap please assign me this issue

**Comment by lakhan06** [comment]
@SurajPratap10 PLease mearge this pull request so that i can work on more issues and can contributer faster to move forward

**Comment by lakhan06** [comment]
@SurajPratap10 Please merge my pull request

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Comment by lakhan06** [comment]
> LGTM

sorry but can't understood this😅

**Pull request merged**
