### PR TITLE
💡 [FEAT]: ACCESSIBLE SOCIAL ANCHORS W/ A11Y PRINCIPLES

### LINKED ISSUE #314: 💡 [FEAT]: ACCESSIBLE SOCIAL ANCHORS FOR FOOTER
**Is your feature request related to a problem? Please describe.**
- This feature is related to accessibility

**Describe the solution you'd like**
- The solution is making the social anchors accessible so that the site may follows best accessibility practices

**Description**

- This issue is about adding `aria-label` for social anchors (links like Github) which are placed inside the `footer` element

- it is important to note that we want to add the `title` attribute also. This is because the `title` attribute is intended to provide additional information to screen reader users.

- The `aria-label` attribute is a way more important for providing accessibility information to screen reader users. The `aria-label` attribute is an Accessible Rich Internet Applications (ARIA) attribute that can be used to provide a label for an element. This label is then read aloud by screen readers, providing additional information about the element to the user.

- In general, the `aria-label` & `title` attributes are preferred for providing accessibility information to screen reader users.

- You can consider to assign this issue to me to make the site accessible for screen readers

**Screenshot (Going to make changes on these elements)**

image

----

**Additional Context**
- I would like to work on this issue, So please make sure to assign this issue to me so that i can start further progress.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
# Description

The issue is about making accessible social anchor elements which are crucial for every site, by following `A11y` principles

## Changes we made
- Added `aria-label` attribute for social anchors like github & twitter
- The `aria-label` attribute is important for screen readers because it provides a text label for an object, such as `a` with social icons. When a screen reader encounters the object, the `aria-label` text is read so that the user will know what it is. 
- This is important for people who are blind or have low vision, as they rely on screen readers to access the web.
- Improved `title` attribute's data, because the title attribute is intended to provide additional information to screen reader users.
- And along with that i added `rel` for the anchors which are lacking them to ensure best practices for crawlers
- Because adding the `rel="noopener noreferrer"` attribute can help to protect this website from security vulnerabilities and improve performance. It is a good practice to use this attribute on all external links.
- Overall this PR is intended to make necessary changes to meet best practices for crawlers along with improving accessibility for social anchors

## Screenshots
- We can't take screenshots of accessibility changes rather than code changes, Accessibility changes are often invisible to the user because it's intended to guide disabled people

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Will check this by tom @0xabdulkhalid 👍

**Comment by 0xabdulkhalid** [comment]
Hello @SurajPratap10, can you review this PR now ?

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
Screenshot_2023-06-24-16-41-45-346_com android chrome


Check the deployment @0xabdulkhalid

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Pull request merged**
