### PR TITLE
 Issue #75-Make the LOGIN page functional

### PR DESCRIPTION
**Pull request by Shounmay**
https://github.com/SurajPratap10/Imagine_AI/assets/90774417/ec1a7094-23f2-41d8-897c-bbbd88c4eeb0

<h3> The above video is demo of Login  and signup functionality. Video starts from 0.03s, sorry for that. Here I have made a Db on Mongo and the URl for that is exposed in .env file. </h3>
<h2> Functionalities </h2>
<li>User can sign-up(register) in the website. Name should be 5 char long, should be a valid email and password must be minimum 8 char long with atleast 1 uppercase,1 lowercase,1 digit</li>
<li> In signup case all these checks are done in backend-server</li>
<li>In signup and login, user can't submit without filling the inputs.</li>
</li>For any kind of error, user will get an error toast notification at the bottom</li>
<li>In case of success in signup/login the user will be redirected to homepage(index.html). This redirection is slow due to absence of optimized reconciliation algorithms(like reactjs uses it) </li>
<h2> Security Issues and Further Enhancements </h2>
<li> If merged, then the .env file can expose the DB URI. So just remove the part of URI after merging and paste it in deployed server environment variable</li>
<li> frontend enhancement for showing password can be done </li>
<li>feature  enhancement for confirm password feature in signup can be done </li>

<h3>Please take a look and review it, i have tried to implement both signup and login functionalities.</h3>

### CODE REVIEW

**Comment by Shounmay** [comment]
Hey Now is there any issue?

**Comment by SurajPratap10** [comment]
Ya, just view the deployed site @Shounmay  and compare it with the current site. Whole fronted is broken

**Comment by SurajPratap10** [comment]
No need to hurry take your time ✌ @Shounmay

**Comment by Shounmay** [comment]
Please check now...

**Comment by SurajPratap10** [comment]
Better, but the 'footer* is broken. View the deployed site for bugs

**Comment by Shounmay** [comment]
Could you please share a screenshot for that footer bug? In my site and deployed I cant see any difference in footer part

**Comment by Shounmay** [comment]
Hey @SurajPratap10 ?

**Comment by SurajPratap10** [comment]
Screenshot_2023-05-25-16-02-22-216_com android chrome


@Shounmay

**Pull request closed without merging**
