### PR TITLE
Add subscribe to email 

### LINKED ISSUE #1289: Roll out mails when subscribing
**Is your feature request related to a problem? Please describe.**
Users should receive subscribing mails to their valid mail ids if  they subscribe the platform.

**Describe the solution you'd like**
I will add backend implementation for sending mails to users.

Screenshot 2024-10-19 165233

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Description
This PR sends mail to user when they subscribe to the platform also receive  a confirmation toast.

 Fixes #1289 

## Screenshots

Screenshot 2024-10-21 151525
Screenshot 2024-10-21 152215
WhatsApp Image 2024-10-21 at 3 24 18 PM

## Checklist

- [X] Tests have been added or updated to cover the changes
- [X] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [X] All tests are passing

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Review by SurajPratap10 — COMMENTED** [review]
image

**Comment by haseebzaki-07** [comment]
@SurajPratap10 did you add the fields EMAIL_USER and EMAIL_PASS in the .env file?? because it is the email through which the mails are sent.

**Comment by SurajPratap10** [comment]
> @SurajPratap10 did you add the fields EMAIL_USER and EMAIL_PASS in the .env file?? because it is the email through which the mails are sent.

Yes, the fields are already present in the env file, you can check it too

**Comment by haseebzaki-07** [comment]
@SurajPratap10 I don't know what wrong with you, but works very fine for me

Screenshot 2024-10-22 112651

https://github.com/user-attachments/assets/ac7d07bf-70b2-4e1f-bc01-e73f0a00a525

**Comment by haseebzaki-07** [comment]
hey @SurajPratap10 please check

**Comment by haseebzaki-07** [comment]
hey @SurajPratap10 please review

**Comment by haseebzaki-07** [comment]
@SurajPratap10 I think it is because of the localhost api call on the frontend , we need to make call to the production url

**Comment by haseebzaki-07** [comment]
hey @SurajPratap10 please check this PR

**Comment by haseebzaki-07** [comment]
hey @SurajPratap10 I have to work with other issues on the site, please finalize this!!

**Comment by haseebzaki-07** [comment]
hey @SurajPratap10 please finalize this PR

**Comment by haseebzaki-07** [comment]
hey @SurajPratap10 I have made the chages, Please check!

**Pull request closed without merging**
