### PR TITLE
Create NEW LANDING PAGE

### PR DESCRIPTION
**Pull request by AyushiTaralkar**
NEW Design for Landing Page

# Description

A modern, visually engaging landing page designed for seamless navigation, featuring bold visuals, clear messaging, and intuitive calls-to-action. It enhances user experience by providing a clean, professional interface that highlights key features and promotes easy interaction.

Figma link : https://www.figma.com/design/HwomNLG1sKE32VEs2TX8U1/Untitled?node-id=0-1&t=N8NtF9j6Fem4u5Uz-1

## Fixes #(issue_no)

#1212

## Screenshots
BEFORE 

Screenshot 2024-10-13 120325

AFTER
Screenshot 2024-10-13 115737

HOPE YOU LIKE IT ...
THANK YOU 
(#1212 )

### CODE REVIEW

**Review by SurajPratap10 — COMMENTED** [review]
It's great you can try mergin it to the main website but do take care of NAVBAR sections like  we  have home,login,dall e etc which you have to add in figma too

**Comment by AyushiTaralkar** [comment]
Thank you . 
I have made the changes you mentioned .

Screenshot 2024-10-13 175539
Screenshot 2024-10-13 175446


ISSUE NO. #1212

**Comment by SurajPratap10** [comment]
ok, but can't u merge the figma design to the project @AyushiTaralkar  as that'll be an easy `level3` for u

**Comment by AyushiTaralkar** [comment]
Yaa I will give you the code for this design that  can be merged ... within 2,3 days .... @SurajPratap10

**Pull request closed without merging**
