### PR TITLE
Change Ui of card in home page

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have change ui of the cards in home page.
Issues #238 .

https://github.com/SurajPratap10/Imagine_AI/assets/132778037/cdd14ff3-5e21-4884-9e2c-d8e143eb1c9a

Kindly inform me if you wanna any other changes.

### CODE REVIEW

**Comment by Pragati-3003** [comment]
> I have change ui of the cards in home page. Issues #238 .
> 
>  IMAGINE.-.AI.-.Google.Chrome.2023-06-07.00-13-26.mp4 
> Kindly inform me if you wanna any other changes.

@SurajPratap10 please review and merge this PR.

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve the conflicts first @Pragati-3003

**Comment by Pragati-3003** [comment]
> Resolve the conflicts first @Pragati-3003

@SurajPratap10  , I have resolved all the merge conflicts ,please check and merge .

**Comment by SurajPratap10** [comment]
The current effect is smooth and necessary , this one is a bit funky and glitchy so I am closing this PR

**Pull request closed without merging**
