### PR TITLE
Added aria attributes to login and signup forms

### LINKED ISSUE #580: Add ARIA attributes to login and signup forms
**Is your feature request related to a problem? Please describe.**
ARIA attributes are crucial for enhancing web application accessibility, benefiting users with disabilities. Currently, our forms lack these attributes, hindering proper interpretation by assistive technologies.

**Describe the solution you'd like**

**Some steps to implement this enhancement-**

- Identify the login and signup form elements in your codebase.
- Determine the relevant ARIA attributes to add for each form element.
- Add ARIA roles to the forms and their elements (e.g., "form" role for the main form element).
- Include concise and descriptive ARIA labels using the aria-label attribute.
- Use the aria-describedby attribute to provide additional instructions for the forms.
- Implement ARIA states and properties (e.g., aria-required for required fields).
- Test the accessibility improvements using assistive technologies.

### PR DESCRIPTION
**Pull request by Avinash905**
# Description

Added aria attributes like aria-label, role, aria-describedby to all form components of login and signup forms

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Avinash905** [comment]
@SurajPratap10 Could you please add level2 to this pr if possible?

**Review by SurajPratap10 — APPROVED** [review]

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve Conflicts

**Comment by Avinash905** [comment]
> Resolve Conflicts

Done

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve Conflicts @Avinash905

**Comment by Avinash905** [comment]
@SurajPratap10 Done

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
