### PR TITLE
Implement #7

### PR DESCRIPTION
**Pull request by rutujp78**
https://github.com/SurajPratap10/Imagine_AI/assets/76244494/654aafe7-204d-49ae-8229-7856c6a5f88b

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Everything's fine now @rutujp78  just the left-out space in the `Generate Button` doesn't look good so just enhance it

image

**Comment by rutujp78** [comment]
Fix the "Generate" button CSS
Screenshot (153)

**Comment by SurajPratap10** [comment]
You can check on the `vercel bot` deployed site here the GENERATE button has not been fixed and in your PR the Try button is also overlaying out of the about section

**Comment by SurajPratap10** [comment]
Just check out the website now @rutujp78 , folks have made the ABOUT section responsive so just put your code there and style the `SURPRISE` me button such that the other buttons don't get affected.

- Then raise a PR I will merge yours first as the site is constantly updated by the PRs of other folks.

**Pull request closed without merging**
