### PR TITLE
Create Chatbot Integrations: Fix issue #1269

### PR DESCRIPTION
**Pull request by mansiruhil13**
Before

Screenshot 2024-10-18 002642

After

Screenshot 2024-10-22 015738

### CODE REVIEW

**Comment by mansiruhil13** [comment]
Can you review please? and merge PR? @SurajPratap10

**Comment by mansiruhil13** [comment]
> Can you review please? and merge PR? @SurajPratap10

and assign with label gssoc and hacktoberfest??

**Comment by SurajPratap10** [comment]
It's not working @mansiruhil13 , you can check on the preview site

**Comment by mansiruhil13** [comment]
its' working
Screenshot 2024-10-22 015738

**Comment by mansiruhil13** [comment]
??

**Pull request closed without merging**
