### PR TITLE
Imagine ai update button doc

### LINKED ISSUE #1361: Adding a Back to Home Feature and improve UI of  Contact-Us Page.
Whenever someone will find the website interesting and would like to contact us, after that , they would like to return to the original home page to explore more. 

**Describe the solution you'd like**
It would be great if the would be back to home button or just the logo showing so that it would redirect the user to the home page

Screenshot 2024-10-30 142629
Improving the UI here too.

### PR DESCRIPTION
**Pull request by ankitmodanwall**
# Description
I have made some changes inside button doc that are following
👉🏻 Front page of button changed totally
👉🏻Updates user experience with BG and hover and more
👉🏻updates toggles buttons color and BG 
👉🏻made other changes 

## Screenshots

|        BEFORE        |        AFTER         |
| :------------------: | :------------------: |
| 
Screenshot 2024-10-30 134731
 |
Screenshot 2024-10-30 132606

## Checklist

- [✅] Tests have been added or updated to cover the changes
- [✅] Documentation has been updated to reflect the changes
- [✅] Code follows the established coding style guidelines
- [✅] All tests are passing

### CODE REVIEW

**Review by ankitmodanwall — COMMENTED** [review]
Please Look into changes once..with ss

**Comment by SurajPratap10** [comment]
You need to show changes on the project you are working, this ain't my project

**Review by SurajPratap10 — COMMENTED** [review]
IDK why there is 30k lines of addition. makes no sense

**Comment by ankitmodanwall** [comment]
So sorry for having glitches and misunderstanding with these project as soon as I will update you with changes ...

**Pull request closed without merging**
