### PR TITLE
Added SideBar for Small device with hamburger icon

### LINKED ISSUE #388: sidebar for small devices to make it better responsive
**Is your feature request related to a problem? Please describe.**
I want to a sidebar for small devices to make it responsive.

**Describe the solution you'd like**
I will add a hamburger icon which is visible when we go to small devices and on clicking that sidebar will come from side with a smoothing transition .

**Describe alternatives you've considered**
Their is no logo of website on the navbar so icon so i can add logo their also

**Additional context**
@SurajPratap10 I am writing to kindly request your attention and consideration in reviewing and accepting issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

### PR DESCRIPTION
**Pull request by lakhan06**
# Description

Enhance the responsiveness of the website by implementing a sidebar for small devices. Introduce a visually appealing hamburger icon that becomes visible when viewed on small devices. Upon clicking the hamburger icon, smoothly slide the sidebar in from the side, providing easy navigation options to the user. This improvement will enhance the overall user experience and make the website more accessible on different screen sizes.

## Screenshots

https://github.com/SurajPratap10/Imagine_AI/assets/119161467/7fb6b6db-ddc8-446f-b1f5-f5d8c282fbfe

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by lakhan06** [comment]
@SurajPratap10 I am writing to kindly request your attention and consideration in reviewing and accepting Pull request. I would greatly appreciate it if you could allocate some time to review the Pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by lakhan06** [comment]
@SurajPratap10 please merge this pull request

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve the `conflicts` @lakhan06

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Comment by lakhan06** [comment]
@SurajPratap10 🥲

**Pull request merged**
