### PR TITLE
Button Hover Effect

### PR DESCRIPTION
**Pull request by SONA-1111**
Task Completed!!
btnn

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Nice @SONA-1111  but you have changed the `border radius` of the  `Generate` button, just see the present website and fix the button accordingly

**Comment by SurajPratap10** [comment]
You need to resolve the conflicts @SONA-1111 , check the web preview and do the needful

**Comment by SONA-1111** [comment]
> You need to resolve the conflicts @SONA-1111, check the web preview, and do the needful rest the button is right. 👍

Can you please provide me with more details about where the problem lies? Because the code seems correct.

**Comment by SurajPratap10** [comment]
> > You need to resolve the conflicts @SONA-1111, check the web preview, and do the needful rest the button is right. 👍
> 
> Can you please provide me with more details about where the problem lies? Because the code seems correct.

- Current 
image


- After your update
image



so just make the changes keeping the `current` pic in mind

**Pull request closed without merging**
