### PR TITLE
Added  tutorial video with custom thumbnail

### LINKED ISSUE #760: Adding Tutorial Video for Obtaining OpenAI API Key and Image Generation on ImagineAI Website
**Issue Description:**

Our ImagineAI website aims to provide users with a seamless experience in generating images using the OpenAI API. To enhance user onboarding and guide them through the process of obtaining an API key and generating images through prompts, we propose adding a tutorial video to the website.

**Proposed Solution:**

We suggest creating a comprehensive tutorial video that walks users through the following key steps:

1. **Obtaining OpenAI API Key:**
   The tutorial will guide users on how to sign up for an OpenAI account (if not already done) and navigate to the API section. It will demonstrate the process of creating a new API key, highlighting the importance of securing and protecting the key.

2. **Setting Up API Key:**
   The tutorial will provide clear instructions on how to add the obtained API key to their ImagineAI account. It will cover where to input the API key and how to save the settings.

3. **Generating Images through Prompts:**
   Users will learn how to formulate effective prompts to generate specific types of images. The tutorial will show how to input prompts, choose parameters, and initiate the image generation process.

4. **Interpreting Results:**
   The video will guide users on how to interpret the generated images, providing tips on optimizing prompts for desired outcomes.

**Expected Benefits:**

By adding this tutorial video to the ImagineAI website, we anticipate several benefits:

1. **Enhanced User Onboarding:** New users will have a clear and visual guide on how to set up their API key and generate images, reducing confusion during the initial interaction.

2. **Reduced Barrier to Entry:** Users unfamiliar with API usage will find it easier to get started and generate images, leading to increased engagement with the platform.

3. **Time Savings:** Users will spend less time troubleshooting and seeking external resources, as the tutorial will provide a consolidated guide.

4. **Improved User Satisfaction:** The tutorial will contribute to a positive user experience and foster confidence in using ImagineAI's capabilities.

**Additional Information:**

- Priority: High
- Target Audience: All users, especially those new to the OpenAI API and image generation through prompts.
- Video Duration: Approximately 5-7 minutes.
- Video Format: Screen recording with narration.

**Implementation Plan:**

1. Identify the key steps and points to cover in the tutorial video.
2. Create a script for the narration, ensuring it is clear, concise, and easy to understand.
3. Record the screen capture video, following the script and demonstrating each step.
4. Edit and refine the video for clarity and brevity.
5. Integrate the video into the ImagineAI website's relevant sections, such as the "Getting Started" or "Tutorials" page.

We believe that adding this tutorial video will significantly improve user onboarding and usage of the ImagineAI platform, ensuring that users can fully leverage the capabilities of the OpenAI API for image generation. Your support and collaboration in creating and implementing this tutorial video are highly appreciated.

If there are any additional suggestions or considerations, please feel free to share them in the discussion.

### PR DESCRIPTION
**Pull request by Nishitbaria**
# Description

## Fixes #760 

Replace `issue_no` with the issue number which is fixed in this PR

Our ImagineAI website aims to provide users with a seamless experience in generating images using the OpenAI API. To enhance user onboarding and guide them through the process of obtaining an API key and generating images through prompts, we propose adding a tutorial video to the website.

We suggest creating a comprehensive tutorial video that walks users through the following key steps:

1. **Obtaining OpenAI API Key**: The tutorial will guide users on how to sign up for an OpenAI account (if not already done) and navigate to the API section. It will demonstrate the process of creating a new API key, highlighting the importance of securing and protecting the key.

2. **Setting Up API Key**: The tutorial will provide clear instructions on how to add the obtained API key to their ImagineAI account. It will cover where to input the API key and how to save the settings.

3. **Generating Images through Prompts**: Users will learn how to formulate effective prompts to generate specific types of images. The tutorial will show how to input prompts, choose parameters, and initiate the image generation process.

4. **Interpreting Results**: The video will guide users on how to interpret the generated images, providing tips on optimizing prompts for desired outcomes.

By adding this tutorial video to the ImagineAI website, we anticipate several benefits:

- Enhanced User Onboarding: New users will have a clear and visual guide on how to set up their API key and generate images, reducing confusion during the initial interaction.
- Reduced Barrier to Entry: Users unfamiliar with API usage will find it easier to get started and generate images, leading to increased engagement with the platform.
- Time Savings: Users will spend less time troubleshooting and seeking external resources, as the tutorial will provide a consolidated guide.
- Improved User Satisfaction: The tutorial will contribute to a positive user experience and foster confidence in using ImagineAI's capabilities.

### Tutorial Video

https://github.com/SurajPratap10/Imagine_AI/assets/85815172/bf5b7a4a-65ac-4c6d-a5d4-bd1500e01388

###  Webiste Video 

https://github.com/SurajPratap10/Imagine_AI/assets/85815172/6b34cc43-8604-429d-bb6b-b027b90d93dd

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,i have made amazing tutotial video and added it on home page ,please review and merge my pull request

**Comment by SurajPratap10** [comment]
There are many problems like `text overlapping` , `video format` etc. You can check them on the deployed site @Nishitbaria

**Comment by Nishitbaria** [comment]
> There are many problems like `text overlapping` , `video format` etc. You can check them on the deployed site @Nishitbaria

solving asap

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,i have updated text  ,now please review and merge my pull request and assign level3 if you think this is essential contribution

**Comment by SurajPratap10** [comment]
@Nishitbaria `video` playing functionality not working

**Comment by Nishitbaria** [comment]
@SurajPratap10,please review and merge my pull request,

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
