### PR TITLE
Update style.css

### LINKED ISSUE #456: Contact page is not fully responsive.
**Kindly assign me this issue. I would like to work on it with the label [GSSoC] .**

The Contact page is not responsive on the Mobile View. I want to fix it.

#Screenshot

Screenshot 2023-06-26 175640

### PR DESCRIPTION
**Pull request by shrutigolwalk0109**
I have use Media query to make contact page responsive for some mobile screen sizes.

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #456 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

https://github.com/SurajPratap10/Imagine_AI/assets/132553685/3bea62a7-2e01-4187-9974-3e487ec456b9

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
Provide a pic of the section you updated @shrutigolwalk0109

**Comment by shrutigolwalk0109** [comment]
Screenshot/ Video:
@SurajPratap10 
https://github.com/SurajPratap10/Imagine_AI/assets/132553685/a70bdc74-c94e-4a24-b9f5-1044d9843dee

**Comment by shrutigolwalk0109** [comment]
@SurajPratap10  I have attached the video in the above comment.

**Comment by SurajPratap10** [comment]
> @SurajPratap10 I have attached the video in the above comment.

Ok , got ya

**Pull request merged**
