### PR TITLE
Changed the user interface of the newletter signup

### PR DESCRIPTION
**Pull request by shriyadindi**
# Description

I've changed the user interface of the newsletter section and increased the height of the section, and changed the color palette to linear gradient and changed the text font.

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by SurajPratap10** [comment]
share pics

**Comment by SurajPratap10** [comment]
Resolve conflicting files..

**Comment by shriyadindi** [comment]
@SurajPratap10 resolved the conflicts

**Comment by aslams2020** [comment]
merged https://github.com/sanjay-kv/Open-source-Practice/pull/1533

**Pull request closed without merging**
