### PR TITLE
changes-made-home-page

### LINKED ISSUE #403: [style]: Text and Button On Home Page Not Aligned and Properly Spaced.
### What's the style idea?

We need to improve the text alignment  and Call to Action button on the Main Page Hero Section.
Padding and Alignment needs to be improved.

### Add screenshots

image
As we can see the text is not aligned properly so it needs to be improved.
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chinmayjain08**
# Description

The text alignment and Call to Action button on the Main Page Hero Section are now correctly positioned and aligned.
Padding and Alignment are taken care of.

## Screenshots:

home-page :

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by chinmayjain08** [comment]
this solves #403 with no merge conflicts

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve the conflicts first @chinmayjain08

**Comment by chinmayjain08** [comment]
Okay I will resolve them.

**Comment by chinmayjain08** [comment]
@SurajPratap10 I have resolved all conflicts, now the PR can be merged.

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
