### PR TITLE
New Section added

### PR DESCRIPTION
**Pull request by PR1YAM9**
hey @SurajPratap10 
i have done the required changes , please check

### CODE REVIEW

**Comment by PR1YAM9** [comment]
@SurajPratap10 its working fine , in both phone and browser

**Comment by SurajPratap10** [comment]
> @SurajPratap10 its working fine , in both phone and browser

It's not working on `Chrome` for me and it's fully broken.

**Comment by PR1YAM9** [comment]
@SurajPratap10 it is looking fine for me in chrome only 

image


image

**Comment by PR1YAM9** [comment]
@SurajPratap10 kindly look into it

**Comment by SurajPratap10** [comment]
Resolve the `views/home.ejs` conflict first @PR1YAM9

**Comment by PR1YAM9** [comment]
@SurajPratap10 i have resolved the conflicts

**Comment by PR1YAM9** [comment]
@SurajPratap10 Kindly look into this PR as it is working fine

**Comment by PR1YAM9** [comment]
@SurajPratap10 Kindly look into this PR as it is working fine

**Pull request closed without merging**
