### PR TITLE
[Fixed]: Removed bootstrap clashes with navbar class

### PR DESCRIPTION
**Pull request by PranavSikarwal**
# Description
1. There were different navbar on home and other pages, due to Bootstrap import clashes.
2. Cards Styling were clashing due to bootstrap.
Before:
image
After:
image

* Fixes: #194 *

## Screenshots

Before: Navigation bar is bigger in height, Dalle OpenAI and Login are not centered
image

After:
image

You can also Check for the testing deployment below:
https://imagine-6grpasviu-pranavsikarwal.vercel.app/

This could be merged on priority, so that no more clashes on home.ejs are faced. (Removing bootstrap which caused clashes)

## Checklist

- [x] Removed the Bootstrap clashes and it's imports.
- [x] Checked for the Deployment after changes were made

### CODE REVIEW

**Comment by PranavSikarwal** [comment]
@SurajPratap10 Convey if any changes further needs to be done, Thanks

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
Can you check the live deployed site @PranavSikarwal  as I'm seeing the before image u sent. Earlier it was okay ig

**Comment by PranavSikarwal** [comment]
@SurajPratap10 , this is not caused by any of my code, this was present earlier also.

**Comment by SurajPratap10** [comment]
> @SurajPratap10. i have just removed bootstrap links:
> It fixes the navbar,
> 
> Cards behave differently on chrome vs firefox :-
> cards are not fixed, they remain as they were earlier,
> On chrome:-
> image
> 
> On Firefox:
> image
> 
> You can revert it but it will make no sense as earlier this card issue was also present on chrome.
> Bootstrap is no more required whereas.

Ya, I was just confirming that only as I'm out now and on my phone there's only chrome browser so I'm not able to see the Firefox version. So it's working fine no @PranavSikarwal ?

**Comment by PranavSikarwal** [comment]
@SurajPratap10 ya sure i will completely agree with you anyways.
Thanks for you support in such conditions also.

**Comment by SurajPratap10** [comment]
> @SurajPratap10 ya sure i will completely agree with you anyways.
> Thanks for you support in such conditions also.

Welcome, you folks are also amazing keep going @PranavSikarwal  ✌

**Pull request merged**
