### PR TITLE
Footer #13

### PR DESCRIPTION
**Pull request by 9520prashant**
Now Footer Looks Better

### CODE REVIEW

**Comment by SurajPratap10** [comment]
@9520prashant  add demo pics

**Comment by SurajPratap10** [comment]
Great!!

**Comment by 9520prashant** [comment]
@SurajPratap10 Now I have to add demo or not Because it merged.

**Comment by SurajPratap10** [comment]
> @SurajPratap10 Now I have to add demo or not Because it merged.

leave it

**Pull request merged**
