### PR TITLE
updated Contact Us - values of phone no. and email address from home …

### LINKED ISSUE #703: [Bug] - Contact Us still has dummy values of phone no. and email address unlike home page
**Describe the bug**
The contact Us still has dummy values of phone no. and email address unlike home page, I can add the actual phone number that is in the home page and the email id of @SurajPratap10 .

image

**To Reproduce**

1. Go to Contact US Page
2. See error

**Expected behavior**
It must have included the Phone number and email address like it does in the home page

**Screenshots**
Added above

**Additional context**
Please assign me this issue under GSSoC'23

### PR DESCRIPTION
**Pull request by 1Shubham7**
…page

# Description

## Screenshots

Before -
image

After -

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by 1Shubham7** [comment]
@SurajPratap10 Please have a look

**Comment by SurajPratap10** [comment]
give number as `9304107324`

**Comment by 1Shubham7** [comment]
Done @SurajPratap10

**Comment by SurajPratap10** [comment]
resolve the `conflicts`

**Comment by 1Shubham7** [comment]
Done @SurajPratap10 .

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
