### PR TITLE
fix: bad contrast color for link on footer 🛠

### LINKED ISSUE #636: [BUG]: IMPROPER TEXT CONTRAST FOR LINK ON FOOTER 🪲
**Describe the bug**
- The bug is improper color used for the `Imagin-AI` link on Footer.
- The text is not visible on normal state, on hover state it completely turns black and gives a bad impression on User Interface.

**To Reproduce**
- Just head to Imagin-AI Website and explore the color contrast used for link on footer

**Expected behavior**
- The text color needs to we have a well contrast so that every user can a able to look it without straining their eyes.

**Screenshots**
https://github.com/SurajPratap10/Imagine_AI/assets/92252895/6bb08e53-441f-4710-a371-b2dd5e12367d

**Desktop (please complete the following information):**

- OS: ArchCraft Linux
- Browser: Mozilla Firefox
- Version: 114

**Smartphone (please complete the following information):**

- Device: Lg Q Stylus
- OS: Android 8
- Browser: Opera Mobile
- Version: 76

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
# Description
- This PR is about fixing the bad contrast color applied for link on footer, the color applied during the hover state also seems to be have a bad contrast.
- I have updated the colors with good contrast which matches the footers background as well, take a look at below table

|NORMAL STATE | HOVER STATE |
|:--: | :---: |
| $\textcolor{yellow}{\textsf{Imagine-AI}}$ | $\textcolor{#2cceff}{\textsf{Imagine-AI}}$  |

## Screenshots

https://github.com/SurajPratap10/Imagine_AI/assets/92252895/c87c6f55-2bcb-4084-a82e-714cc1ea607c

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hey there @SurajPratap10 👋🏻

Please make sure to review this PR.

Thank you..!

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
Resolve Conflicts

**Comment by 0xabdulkhalid** [comment]
@SurajPratap10 the Conflicts are resolved 🎉

**Comment by SurajPratap10** [comment]
Why you have changed so many lines?

**Comment by 0xabdulkhalid** [comment]
@SurajPratap10 I formatted the code to maintain code consistency.

**Comment by SurajPratap10** [comment]
> @SurajPratap10, Yeah i forget to mention that I have also formatted the code with best practices to maintain code consistency.
> 
> Can you provide `level2` for the changes i done, because i refactored the code.

OK

**Pull request merged**
