### PR TITLE
Laibaahsan

### PR DESCRIPTION
**Pull request by laibaahsan27**
Hiii
I made the following changes on the about page as promised:
1) fixed the allignment of heading and the text.
2) adjusted the spacing between elements.
3) made the whole page 100% responsive.
4) did few changes to make the UI/UX look better for the user experience.
please let me know if you want to change anything.
Thank You

### CODE REVIEW

**Comment by laibaahsan27** [comment]
@SurajPratap10 sir what this comment mean? Did you find the changes upto the mark?

**Comment by SurajPratap10** [comment]
> @SurajPratap10 sir what does this comment mean? Did you find the changes upto the mark?

Which comment ??

**Comment by SurajPratap10** [comment]
image


Resolve these `CONFLICTS` @laibaahsan27  as you only have permission to do this and while raising a PR just put the change/feature u added in the `Title`

**Comment by PranavSikarwal** [comment]
@laibaahsan27 i can help you with it, basically many pr's were merged and some major changes were made to the project.
You can reach me out on discord: 
copy my username
PЯДИДV#6001

Suggestion: Make a new pr after sync the main branch and again adding the changes.

**Comment by laibaahsan27** [comment]
i have an exam tomorrow so i will get it done after that. @PranavSikarwal i will get in touch with you tomorrow.

**Pull request closed without merging**
