### PR TITLE
Updated ImaginAi Page & Remove Bugs

### LINKED ISSUE #547: [style]: Want to Improve Imagin-AI Page and also spelling errors and aligning issues
### What's the style idea?

We need to improve the Improve AI Page. There are some issues in this page.

### Add screenshots

Add screenshots

WhatsApp Image 2023-07-06 at 5 26 20 PM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by killerraj369**
# Description

Hey Project Admin,
I have removed the bugs that were present in the imagin-AI page. There were many aligning issue as well as issues in FAQs whom I have fixed.

## Fixes #547 

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ X] Tests have been added or updated to cover the changes
- [ X] Documentation has been updated to reflect the changes
- [ X] Code follows the established coding style guidelines
- [ X] All tests are passing

### CODE REVIEW

**Comment by killerraj369** [comment]
Hey @SurajPratap10 , if you have reviewed my PR and no changes are required, then please can you merge it.

**Comment by SurajPratap10** [comment]
> Hey @SurajPratap10 , if you have reviewed my PR and no changes are required, then please can you merge it.

Rsolve `conflicts`

**Comment by killerraj369** [comment]
Hey @SurajPratap10 , I have resolved the conflicts, can you please check it..

**Comment by killerraj369** [comment]
@SurajPratap10 I have resolved the conflicts please check and review

**Comment by SurajPratap10** [comment]
Can you elucidate on what bugs u resolved ?

**Comment by killerraj369** [comment]
These were the issues in the page
image
you can see updated page on the photos given above

**Comment by SurajPratap10** [comment]
Ok, just resolve the `conflict and comment

**Comment by killerraj369** [comment]
@SurajPratap10 Resolved

**Comment by SurajPratap10** [comment]
It's still the same ig @killerraj369 

image

**Pull request closed without merging**
