### PR TITLE
The title text as well as other texts in community section changed

### LINKED ISSUE #798: [style]: The title text as well as other texts in "community" section requires change
### What's the style idea?

image

The title size and weight must be improved and also the contributor photos should have border + text should be lighter

### Add screenshots

added above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 1Shubham7**
# Description

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Resolve `conflicts`

**Comment by 1Shubham7** [comment]
opps. Sorry for that. Resolved the conflicts

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
image

Add the `Commits`  text in the gaps I marked in the pic. eg: Commits 366 (in my case)

**Comment by 1Shubham7** [comment]
ok, I didn't add the number of commits, it was not even showing before this. But I will do it 👍

**Comment by SurajPratap10** [comment]
> ok, I didn't add the number of commits, it was not even showing before this. But I will do it 👍

Ya

**Pull request merged**
