### PR TITLE
Show password icon

### LINKED ISSUE #466: [style]: Change Show password Style
### What's the style idea?

I want to change the show password design similar to the below one:

https://github.com/SurajPratap10/Imagine_AI/assets/86224794/35d12c9a-f478-48e7-bfb6-8483aca33154

Also, there is no show password in the sign-up form I will implement it there as well.

Please assign me this issue under gssoc23 if you find this worth implementing

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description

Added show password icon in login and signup form

## Output video

https://github.com/SurajPratap10/Imagine_AI/assets/86224794/c712c99f-0688-4d4c-92bf-b5616817a336

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve the `conflicts`

**Comment by AlfiyaSiddique** [comment]
@SurajPratap10 please review this PR. I have resolved the conflicts.

**Review by SurajPratap10 — COMMENTED** [review]
LGTM

**Pull request merged**
