### PR TITLE
Improved the contact us details section

### PR DESCRIPTION
**Pull request by VidhanThakur09**
Applied styling on icons and improved the Contact Us details section with a hover effect.

- changed the style of icons
- Applied the animation on the Contact Us details section cards
- upgrade icon's
- fix the overflowing details

fix issue #1120

### CODE REVIEW

**Comment by rajveeerr** [comment]
@VidhanThakur09 can you please add screenshots for the reference??

**Comment by SurajPratap10** [comment]
**On mobile view:** 
Screenshot_2024-10-04-07-30-17-117_com android chrome
Make the whole part responsive like the mail IDs etc aren't visible

**On desktop view:**
Screenshot_2024-10-04-07-30-25-736_com android chrome
Fix the thing at the bottom

**Review by SurajPratap10 — COMMENTED** [review]
Fix all those stuff then I'll merge when I see. Looks good 👍

**Comment by VidhanThakur09** [comment]
The space in footer is due to your desktop site active on mobile browser,  please deactivate that . 



And I will be making the contact us details section responsive.

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
