### PR TITLE
Improved landing page, refactored css and dark mode code, improved socials button and dark mode button

### LINKED ISSUE #300: [style]: Making the landing page better
### What's the style idea?

We need to improve the top of the landing page where the description of the website is given. Currently is not looking attracting. I can make this better. Please assign me this issue. I will add screenshots of it. Thank you!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Description

Hey @SurajPratap10 I have improved the landing page, refactored CSS, and dark mode code, and improved the socials button and dark mode button. It took a lot of time to do all these changes. Please review my pr and merge it. Thank you!

## Screenshots

1. Landing Page:-

image

2. Dark mode button:-

image

3. Social button:-

image

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Resolve the conflict @sumitkr2000

**Comment by sumitkr2000** [comment]
abhi 40 conflict h kis kis ko resolve kru

**Comment by SurajPratap10** [comment]
> Bhai maine bola tha ki css refactor kr rha hu fir thoda wait to kr lete

There are so many PRs/issues coming on daily basis that it's not possible to fulfil and remember each folks demand, plus they are too anxious regarding their PRs being merged as soon as they raise it. So, I generally check the PRs at night when I am free with my college and other works.

But still, you can fix the conflicts by tommorow's night if you wish to, as I can't keep rest of the folks waiting for too long 👍.

**Comment by sumitkr2000** [comment]
> > Bhai maine bola tha ki css refactor kr rha hu fir thoda wait to kr lete
> 
> There are so many PRs/issues coming on daily basis, so it's not possible to fulfil and remember each folks demand, plus they are too anxious regarding their PRs being merged as soon as they raise it. So, I generally check the PRs at night when I am free with my college and other works.
> 
> But still, you can fix the conflicts by tommorow's night if you wish to, as I can't keep rest of the folks waiting for too long 👍.

Okay I'll try.

**Comment by SurajPratap10** [comment]
> > > Bhai maine bola tha ki css refactor kr rha hu fir thoda wait to kr lete
> > 
> > 
> > There are so many PRs/issues coming on daily basis, so it's not possible to fulfil and remember each folks demand, plus they are too anxious regarding their PRs being merged as soon as they raise it. So, I generally check the PRs at night when I am free with my college and other works.
> > But still, you can fix the conflicts by tommorow's night if you wish to, as I can't keep rest of the folks waiting for too long 👍.
> 
> Okay I'll try.

Done? as other folks are texting me regarding their PRs @sumitkr2000 ?

**Comment by sumitkr2000** [comment]
bhot jyada kachra ho gya h

**Pull request closed without merging**
