### PR TITLE
Issue #23 : Fixed api key backend functionality

### PR DESCRIPTION
**Pull request by mani200307**
Fixed the backend functionality of api key, Now the api key is taken as input to the generate function.

### CODE REVIEW

**Comment by SurajPratap10** [comment]
image

Not fixed @mani200307

**Comment by SurajPratap10** [comment]
image


Not fixed @mani200307

**Comment by mani200307** [comment]
@SurajPratap10, I'll look into it.

**Comment by SurajPratap10** [comment]
> @SurajPratap10, I'll look into it.

Ya, no need to hurry take your time 👍

**Pull request closed without merging**
