### PR TITLE
Style added on Scrollbar

### PR DESCRIPTION
**Pull request by HimanshuNarware**
# Description
 Style added on the scrollbar.

## Screenshots
solve1

## Checklist
- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve the `conflicts`

**Comment by HimanshuNarware** [comment]
> Resolve the `conflicts

done

**Comment by SurajPratap10** [comment]
The color doesn't look good. Make that minimilistic not funky

**Comment by HimanshuNarware** [comment]
> The color doesn't look good. Make that minimilistic not funky

ok

**Comment by HimanshuNarware** [comment]
> The color doesn't look good. Make that minimilistic not funky

hey@SurajPratap10 which one is looking good 

1.
optionn2

2.
option3

**Comment by SurajPratap10** [comment]
> > The color doesn't look good. Make that minimilistic not funky
> 
> hey@SurajPratap10 which one is looking good
> 
> 
> optionn2
> 
> 
> option3
> 
> option2

2

**Comment by HimanshuNarware** [comment]
@SurajPratap10  changes successfully added according to you

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Resolve `conflicts`

**Comment by HimanshuNarware** [comment]
> Resolve `conflicts`

Done👍

**Comment by SurajPratap10** [comment]
Ig it is happening because of the PRs of other folks, so you just resolve this PR and leave a comment I will merge your PR first. 👍

**Comment by HimanshuNarware** [comment]
@SurajPratap10  Resolved all conflics

**Comment by HimanshuNarware** [comment]
> @SurajPratap10 Resolved all conflics

@SurajPratap10  Merge

> Ig it is happening because of the PRs of other folks, so you just resolve this PR and leave a comment I will merge your PR first. 👍

@SurajPratap10  Merge

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
image


Is it broken? check the deployed site

**Comment by HimanshuNarware** [comment]
> image
> 
> Is it broken? check the deployed site

@SurajPratap10  I checked it's working properly, Ok I have one solution I made another PR for this issue

**Pull request closed without merging**
