### PR TITLE
This PR is related to issue #1324. Feat: terms and service page created

### LINKED ISSUE #1324: Terms of Service page missing.
**Is your feature request related to a problem? Please describe.**
The website is missing a terms of services page as it is important to have one so that user knows about the terms of the services we provide.

**Describe the solution you'd like**
I would like to create  a page maintaining the UI having terms of service information

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Priyank00007**
# Description
I have created a terms and service page with related information and maintaining the UI of the project. Also added the link on footer of all pages.

## Screenshots

 AFTER 

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
image
This needs to be fixed @Priyank00007

**Comment by Priyank00007** [comment]
> image This needs to be fixed @Priyank00007

@SurajPratap10 sir I don't know how to fix it, I saw this error coming and I try to visit the footer file but I couldn't find the exact issue coming so can u help me in figuring out that?

**Comment by Priyank00007** [comment]
@SurajPratap10 sir can u help me regrading the above issue?

**Comment by SurajPratap10** [comment]
> > image This needs to be fixed @Priyank00007
> 
> @SurajPratap10 sir I don't know how to fix it, I saw this error coming and I try to visit the footer file but I couldn't find the exact issue coming so can u help me in figuring out that?

It's just some CSS issue, like u need to fix wdith and stuff

**Comment by Priyank00007** [comment]
> > > image This needs to be fixed @Priyank00007
> > 
> > 
> > @SurajPratap10 sir I don't know how to fix it, I saw this error coming and I try to visit the footer file but I couldn't find the exact issue coming so can u help me in figuring out that?
> 
> It's just some CSS issue, like u need to fix wdith and stuff

Sir I tried my best to find the issue regarding the footer but its working on privacypolicy page but not on this page and the code is entirely same and I have tried many ways to resolve this issue but I am unable to find any result regarding this.

**Pull request closed without merging**
