### PR TITLE
Navfix

### PR DESCRIPTION
**Pull request by PR1YAM9**
HI, @SurajPratap10 thanks again for being patient with me 😭😭. I have made changes and fixed a lot of errors and bugs this time and navbar is working.
reference images: 
image

image

image

image

image

image

If there are any more issues with the navbar kindly tell me, I have devoted a lot of time to it...

### CODE REVIEW

**Comment by SurajPratap10** [comment]
> HI, @SurajPratap10 thanks again for being patient with me 😭😭. I have made changes and fixed a lot of errors and bugs this time and navbar is working. reference images: image
> 
> image image image image image
> If there are any more issues with the navbar kindly tell me, I have devoted a lot of time to it...

No issues @PR1YAM9  it's a 3 month program you can take your time and I can take mine, no need to worry and here just resolve the `conflicts` first

**Comment by PR1YAM9** [comment]
Hi i saw the deployed version and there are still some issues but on my branch (navfix), it is working perfectly can you guide me ?

**Comment by SurajPratap10** [comment]
> Hi i saw the deployed version and there are still some issues but on my branch (navfix), it is working perfectly can you guide me ?

I think this is due to constant updates by the PRs of other folks. Try re-forking the repo and just put you update on it and make a new PR or edit on this if possible

**Comment by PR1YAM9** [comment]
I have checked the deployment somehow it is picking the commented code so I have deleted all the previous code related to navbar

**Pull request closed without merging**
