### PR TITLE
Responsive NavBar Added

### PR DESCRIPTION
**Pull request by PR1YAM9**
I have added a responsive navbar for all the media widths and kept the page's background in mind. Please check it out if there are any changes you want me to make kindly tell me.
Regards Priyam Maini
ps: I think I made the push from the origin and not from remote I am sorry and hope it won't be a problem if it is please guide me on what to do next.

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Resolve the conflicts @PR1YAM9

**Comment by SurajPratap10** [comment]
The current Navbar is nice ig , so we don't need this one at the time @PR1YAM9

**Comment by SurajPratap10** [comment]
The footer is broken @PR1YAM9  just put it back to its original form rest is fine.


image

**Comment by PR1YAM9** [comment]
Okay , i am also going to make another footer under diff issue as well

**Comment by SurajPratap10** [comment]
> Okay , i am also going to make another footer under diff issue as well

Ok when completed then ask for merge✌

**Comment by PR1YAM9** [comment]
I have fixed the Footer class name and link clash kindly look into it

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
Your Navbar was breaking the frontend , kindly check it and make a new pr

**Comment by PR1YAM9** [comment]
I 

> Your Navbar was breaking the frontend , kindly check it and make a new pr

I am sorry about that can you please explain, what is happening in my localhost it is working fine.
image

image

image

I will make sure to correct it as soon as possible

**Comment by PR1YAM9** [comment]
> I
> 
> > Your Navbar was breaking the frontend , kindly check it and make a new pr
> 
> I am sorry about that can you please explain, what is happening in my localhost it is working fine. image
> 
> image image
> I will make sure to correct it as soon as possible

I have understood the issue I am making a new nav bar

**Pull request merged**
