### PR TITLE
Added sitemap.xml

### LINKED ISSUE #453: Adding new Sitemap.xml
**Is your feature request related to a problem? Please describe.**
A sitemap is a file that lists all the pages of a website, helping search engines understand its structure and content. It enhances search engine optimization (SEO) efforts by improving website visibility and indexing. I believe adding sitemap would be a perfect addition to this project.

**Describe the solution you'd like**
Adding the sitemap.xml file in the public folder section.

### PR DESCRIPTION
**Pull request by saikiranreddy201**
# Description

I have added the sitemap.xml file in the public folder for improved SEO.

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Comment by saikiranreddy201** [comment]
Hey @SurajPratap10 please add the gssoc **level** label

**Comment by saikiranreddy201** [comment]
Hey, @SurajPratap10, please add the level label so I can get my points.
Thank you :)

**Comment by saikiranreddy201** [comment]
Hello @SurajPratap10, please don't lag this anymore. please add the level label to my pr.

**Pull request merged**
