### PR TITLE
Contact Page Submit Button #142 Fixed

### PR DESCRIPTION
**Pull request by 9520prashant**
Now Submit button position has been fixed.

Screenshot (251)

### CODE REVIEW

**Comment by 9520prashant** [comment]
@SurajPratap10 solved

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Comment by 9520prashant** [comment]
@SurajPratap10 bro my change does not show in the website Why?

**Comment by SurajPratap10** [comment]
It is @9520prashant  right ?


image

**Comment by 9520prashant** [comment]
yep

**Pull request merged**
