### PR TITLE
cards animated

### PR DESCRIPTION
**Pull request by laibaahsan27**
I deleted the old forked repo, made a new one, did all the changes, checked locally a few times and everything seems fine from my side.

### CODE REVIEW

**Comment by laibaahsan27** [comment]
@SurajPratap10 could you please merge my pr first

**Comment by SurajPratap10** [comment]
> @SurajPratap10 could you please merge my pr first

Will check it in the evening

**Comment by SurajPratap10** [comment]
It's breaking the website @laibaahsan27

**Review by SurajPratap10 — COMMENTED** [review]
LGTM @laibaahsan27

**Pull request merged**
