### PR TITLE
Newsletter Section Added

### LINKED ISSUE #407: [Feature]: Dedicated Newsletter Section to increase engagement with users.
**Is your feature request related to a problem? Please describe.**
No, it is to make the application experience better for the user.

**Feature Enhancement** :
We can create a dedicated section for newsletter to make the homepage more appealing to the viewer/user.
Also it will make the web application more interacting in users perspective.

**Additional context**
A newsletter section can also help to build relationships with visitors and keep them engaged with the website.

### PR DESCRIPTION
**Pull request by chinmayjain08**
# Description

Created a dedicated section for newsletter to make the homepage more interactive to the viewer/user.
Newsletter designed keeping in mind the clean UI design concepts.

## Screenshots

image

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Is it functional? @chinmayjain08

**Comment by chinmayjain08** [comment]
> Is it functional? @chinmayjain08

No, not yet. For now it is just UI .
If you say , I can try making it functional by connecting to google sheets for entries.

**Comment by SurajPratap10** [comment]
> > Is it functional? @chinmayjain08
> 
> No, not yet. For now it is just UI . If you say , I can try making it functional by connecting to google sheets for entries.

Ya, plz do it and then push it via a new PR. for now I am closing this one

**Comment by chinmayjain08** [comment]
> > > Is it functional? @chinmayjain08
> > 
> > No, not yet. For now it is just UI . If you say , I can try making it functional by connecting to google sheets for entries.
> 
> Ya, plz do it and then push it via a new PR. for now I am closing this one

Okay will do it.

**Comment by chinmayjain08** [comment]
@SurajPratap10 actually the link can be established by you only as it it needs authorization to your google account.
And also the newsletter PR(initial one) is merged but no level is provided despite the implementation being done

**Pull request closed without merging**
