### PR TITLE
About us page updated

### PR DESCRIPTION
**Pull request by eshaalal**
Feature added:
1. scroll motion added
2. GSAP used

https://github.com/user-attachments/assets/9931bc99-3bd5-492e-a0af-68de9e6eb6f2

I have added the video

### CODE REVIEW

**Comment by eshaalal** [comment]
@SurajPratap10 i have updated the about us page please have a peek into it

**Comment by eshaalal** [comment]
@SurajPratap10 adding screen shots as well for the part below animation

Screenshot 2024-10-09 224205
Screenshot 2024-10-09 224222

**Review by SurajPratap10 — COMMENTED** [review]
image
you can see various issues like text size, login button size etc. The overall animation is very good but you need to fix these bugs first

**Comment by eshaalal** [comment]
@SurajPratap10  I tried working on that but actually that is happening because of animation

**Comment by SurajPratap10** [comment]
> @SurajPratap10 I tried working on that but actually that is happening because of animation .

`Ya , I know that but I can't make the basic things of the project look weird no cuz of adding some advance animation that's why I told u to optimize it as it makes everything on that page weird the texts , buttons etc.. I didn't close the PR cuz your animation part is really good reason why I am giving u time. Take your time if you can't do it then in few days i'll close this no worries you can work on new issues after then.

`

**Comment by eshaalal** [comment]
> > @SurajPratap10 I tried working on that but actually that is happening because of animation .
> 
> Ya , I know that but I can't make the basic things of the project look weird no cuz of adding some advance animation that's why I told u to optimize it as it makes everything on that page weird the `texts` , `buttons` etc.. I didn't close the PR cuz your animation part is really good reason why I am giving u time. Take your time if you can't do it then in few days i'll close this no worries you can work on new issues after then.
> 
> `

I will work on it

**Comment by eshaalal** [comment]
hey @SurajPratap10 I have updated the code and now all bugs are resolved

Screenshot 2024-10-10 144558
Screenshot 2024-10-10 144619
please have a look

**Comment by eshaalal** [comment]
@SurajPratap10 if you decide to merge this PR, would really appreciate if merged with  hacktoberfest-accepted, gsoc-ext, level-3 labels

**Comment by eshaalal** [comment]
@SurajPratap10 I made the changes you wanted why did you closed the PR

**Pull request closed without merging**
