### PR TITLE
feat: revamp newsletter sign up section 🪄✨ 

### LINKED ISSUE #731: feat: revamp the design of newsletter section ⚒️✨
## Description
- The current look of newsletter section have many number issues in terms of alignment and spacing.
- We need to revamp them into fully fledged Newsletter component without any issues.

## Screenshot (Current State)
image

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
# Description
- Revamped the design of Newsletter Signup Section, Built with Mobile first Workflow.
- So it ensures responsive for Mobile and Desktop.

## Screenshots

|DESKTOP VIEW - OLD| DESKTOP VIEW - NEW|
|:---:|:---:|
|image | image |

|MOBILE VIEW - OLD| MOBILE VIEW - NEW|
|:---:|:---:|
| image | image 

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hey there @SurajPratap10 👋🏻 

Please make sure to review this PR 🏳️

**Comment by SurajPratap10** [comment]
image

**Comment by 0xabdulkhalid** [comment]
@SurajPratap10 Now it's resolved.

It's due Inline styles, You can verify now by testing deployment by authorizing it.

**Comment by 0xabdulkhalid** [comment]
@SurajPratap10 Now it's resolved.

It's due Inline styles, You can verify now by testing deployment by authorizing it.

**Comment by 0xabdulkhalid** [comment]
@SurajPratap10 Now it's resolved.

It's due Inline styles, You can verify now by testing deployment by authorizing it.

Also please assign this issue #734 to me after Merging this PR.

**Review by SurajPratap10 — APPROVED** [review]
LGTM 👍

**Pull request merged**
