### PR TITLE
Issue #75-Make the LOGIN page functional

### PR DESCRIPTION
**Pull request by Shounmay**
https://github.com/SurajPratap10/Imagine_AI/assets/90774417/ec1a7094-23f2-41d8-897c-bbbd88c4eeb0

<h3> The above video is demo of Login  and signup functionality. Video starts from 0.03s, sorry for that. Here I have made a Db on Mongo and the URl for that is exposed in .env file. </h3>
<h2> Functionalities </h2>
<li>User can sign-up(register) in the website. Name should be 5 char long, should be a valid email and password must be minimum 8 char long with atleast 1 uppercase,1 lowercase,1 digit</li>
<li> In signup case all these checks are done in backend-server</li>
<li>In signup and login, user can't submit without filling the inputs.</li>
</li>For any kind of error, user will get an error toast notification at the bottom</li>
<li>In case of success in signup/login the user will be redirected to homepage(index.html). This redirection is slow due to absence of optimized reconciliation algorithms(like reactjs uses it) </li>
<h2> Security Issues and Further Enhancements </h2>
<li> If merged, then the .env file can expose the DB URI. So just remove the part of URI after merging and paste it in deployed server environment variable</li>
<li> frontend enhancement for showing password can be done </li>
<li>feature  enhancement for confirm password feature in signup can be done </li>

<h2> Footer broken Bug </h2>
<li>Hey in my local clone, the footer part works fine.  As discussed raised a new PR, now this part might get resolved.</li>

check_broken_footer

<h3>Please take a look and review it, i have tried to implement both signup and login functionalities.</h3>

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Just check the footer issue, rest is fine @Shounmay

**Comment by Shounmay** [comment]
Hey i have updated the footer code part. please do check it if it resolves the bug @SurajPratap10

**Comment by SurajPratap10** [comment]
Check the deployed site by verbal bot @Shounmay

**Comment by Shounmay** [comment]
Let me raise a new PR, as this preview has just the changes of latest commit, not all the commits

**Pull request closed without merging**
