### PR TITLE
Fix: Styling issue in Login.ejs ✨

### LINKED ISSUE #716: [style]: Improve Login issue
### What's the style idea?

We need to improve  

**I have Improved the styling Which Looks More Good  ✨**  

### Add screenshots

Add screenshots

Before 

image

After 

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Nishitbaria**
# Description

I have added a new icon to the login page also improve some` label `styling in the login form also improve the styling of the `input` tag

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hey @SurajPratap10  PLease Review The PR and Merge it

**Comment by SurajPratap10** [comment]
image

This `sizing` looks better

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,i have fixed sizing ,now you can review and merge my pull request

https://github.com/SurajPratap10/Imagine_AI/assets/85815172/b0f13ef8-1daf-476b-9474-8121fe78d7e9

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,i have fixed sizing and added hover effect ,now you can review and merge my pull request

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
