### PR TITLE
Issue #75-Make the LOGIN page functional

### PR DESCRIPTION
**Pull request by Shounmay**
https://github.com/SurajPratap10/Imagine_AI/assets/90774417/ec1a7094-23f2-41d8-897c-bbbd88c4eeb0

<h3> The above video is demo of Login  and signup functionality. Video starts from 0.03s, sorry for that. Here I have made a Db on Mongo and the URl for that is exposed in .env file. </h3>
<h2> Functionalities </h2>
<li>User can sign-up(register) in the website. Name should be 5 char long, should be a valid email and password must be minimum 8 char long with atleast 1 uppercase,1 lowercase,1 digit</li>
<li> In signup case all these checks are done in backend-server</li>
<li>In signup and login, user can't submit without filling the inputs.</li>
</li>For any kind of error, user will get an error toast notification at the bottom</li>
<li>In case of success in signup/login the user will be redirected to homepage(index.html). This redirection is slow due to absence of optimized reconciliation algorithms(like reactjs uses it) </li>
<h2> Security Issues and Further Enhancements </h2>
<li> If merged, then the .env file can expose the DB URI. So just remove the part of URI after merging and paste it in deployed server environment variable</li>
<li> frontend enhancement for showing password can be done </li>
<li>feature  enhancement for confirm password feature in signup can be done </li>

<h3>Please take a look and review it, i have tried to implement both signup and login functionalities.</h3>

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Very Good @Shounmay  I will merge it just you need to resolve the conflicts first ✌

**Comment by Shounmay** [comment]
But what exactly is conflicting, I unable to view it. It says conflicts are too complex to resolve in web editor. Could you help me in this? @SurajPratap10

**Comment by SurajPratap10** [comment]
> But what exactly is conflicting, I unable to view it. It says conflicts are too complex to resolve in web editor. Could you help me in this? @SurajPratap10 

 I will reply you by tom as I am out for some work now. So I don't have my laptop with me ( and these conflicts are too huge) to be viewed on mobile

**Comment by SurajPratap10** [comment]
image


These are the `Conflicts` @Shounmay  and as you can see I can't resolve them (no permission) so only you have the permission to resolve them.

**Comment by Shounmay** [comment]
Hey review my latest commit. I have resolved all conflicts. Actually due to updating to ejs these conflicts have occurred. Hope for no more conflicts. Please review it.

**Comment by SurajPratap10** [comment]
You can check the `vercel bot deployed site` here @Shounmay it's fully broken .. reason why I told u to make a fresh PR

image

**Pull request closed without merging**
