### PR TITLE
Issue#23: Adding_Functionality_to_Enter_Your_API_Key_section

### PR DESCRIPTION
**Pull request by Shounmay**
Hey I have solved the issue. Now by giving an API_KEY, client can view the generated image.
API_functionality_1
Now if the API_KEY is valid and still active, client can view the generated image that client has prompted and mentioned the size.

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Check by putting the key on the `VERCEL` bot deployed site here @Shounmay , that u are getting the image or not.

**Comment by Shounmay** [comment]
I have checked with the Deployed site and it's working as expected.
deployed_check_API_KEY_Fun_1
Check this out!!!!
I think now this PR can be merged

**Comment by SurajPratap10** [comment]
Kudos @Shounmay  📌

**Comment by SurajPratap10** [comment]
I have merged the PR @Shounmay  now just check again by generating an image by your key and tell me here, as my key is `outdated`

**Comment by Shounmay** [comment]
Working as expected!!!!!! Have a look for this pic
deployed_check_API_KEY_Fun_2
Thanks for giving me a chance for contributing to this issue.
Hope it feature works as you expected!!!!

**Comment by SurajPratap10** [comment]
Appreciate your efforts @Shounmay 🔥 My key is expired so I am not able to test can you plz record a video while generating some pics from the `live site` and raise an issue to put it in the `README` file . I will assign that issue to you.

**Comment by SurajPratap10** [comment]
Are you there @Shounmay ?

**Comment by Shounmay** [comment]
Really Sorry @SurajPratap10,I was actually travelling so couldn't respond to your comments. Yaa I will make a Video on generating images by API KEY in live site. I will update that part in readme of this project. 
Apart from this I feel that API Key shouldn't be exposed as anyone can access the variable that stores the API Key. If you can raise an issue to blur the API Key or make it as password and store the hashed format in the variable.
If you want to test I can provide you my API Key.

**Comment by SurajPratap10** [comment]
NP, and regarding the issue you can raise it ( I will assign it to you) 👍

**Pull request merged**
