### PR TITLE
Added backend support to generate N images

### PR DESCRIPTION
**Pull request by markyasser**
# Generate N images 
* issue #100 

- Added new function  **generateImages** in the file _openaiController.js_ .
- The function generates N images depending on what the user wants.
- Added the function to the routes file.

### CODE REVIEW

**Comment by PranavSikarwal** [comment]
@SurajPratap10  please merge #101 before merging this because i created almost 3-4 new branches and worked multiple times.
This can be easily be redone and merged the next time.
My pr is big hence requires lot of time to make a new pr.

**Comment by SurajPratap10** [comment]
any demo video? @markyasser  plus do make this available keeping in mind the recent website as it keeps on updating via the PRs of other folks

**Comment by markyasser** [comment]
> any demo video? @markyasser plus do make this available keeping in mind the recent website as it keeps on updating via the PRs of other folks

I couldn't make a demo video because I don't have OpenAI key and GPT is not available in my country.
But the function should work properly.

I have synced my branch with the main branch.

**Review by SurajPratap10 — APPROVED** [review]
lgtm

**Comment by SurajPratap10** [comment]
> > any demo video? @markyasser plus do make this available keeping in mind the recent website as it keeps on updating via the PRs of other folks
> 
> I couldn't make a demo video because I don't have OpenAI key and GPT is not available in my country. But the function should work properly.
> 
> I have synced my branch with the main branch.

No issues, good job

**Pull request merged**
