### PR TITLE
Oauth added

### PR DESCRIPTION
**Pull request by AKsHaT123456A**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by AKsHaT123456A** [comment]
Okay will attach a video @SurajPratap10

**Comment by AKsHaT123456A** [comment]
image
image
image
image

**Comment by AKsHaT123456A** [comment]
Hi @SurajPratap10 kindly check the screenshots

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Pull request merged**
