### PR TITLE
Contibutor page issue resolved

### PR DESCRIPTION
**Pull request by HimanshuNarware**
# Description
Contibutor page issue resolved

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by SurajPratap10** [comment]
It should be `commits`

**Comment by HimanshuNarware** [comment]
> It should be `commits`

?

**Comment by SurajPratap10** [comment]
image


instead of commit, put commits

**Comment by HimanshuNarware** [comment]
@SurajPratap10 Commits done

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
