### PR TITLE
Clean: Unwanted scroll to top styling

### LINKED ISSUE #133: [Clean]: Remove Unwanted scroll to top styling.
**As Scroll to top was removed way back in a pr, hence it is needed to remove it's styling present in style.css**

**This Make the style.css file less cumbersome**

image

### PR DESCRIPTION
**Pull request by PranavSikarwal**
**This PR makes the following changes.**
* Fixes #133  *

The Scroll To Top functionality was removed way back in a PR but it's styling was making style.css file more cumbersome, so removed the scroll to top styling.

### CODE REVIEW

**Comment by PranavSikarwal** [comment]
@SurajPratap10 you may merge this branch to clean scroll to top styling as it is unwanted, no scroll to top button needed now

**Comment by SurajPratap10** [comment]
RESOLVE CONFLICTS @PranavSikarwal

**Comment by PranavSikarwal** [comment]
@SurajPratap10 merged the changes, thanks...

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Pull request merged**
