### PR TITLE
resolve theme & activetab issue

### LINKED ISSUE #620: Theme icon and active tab
**Describe the bug**
 In this project there is missing of active tab class in about and contact us page .
Also theme icon in contact  us page is not work.

**To Reproduce**

**Expected behavior**
When about page is open it has to shows active class at active and when contact page shows active class at the contact page.
Also when clicked to theme icon in contact page it has to change the theme.

**Screenshots**
Screenshot 2023-07-17 141600
Screenshot 2023-07-17 141615

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by BhartiNagpure**
# Description

I'm resolve the issue related to theme and active tab for pages :
1 Imagine AI -> theme
2 About Us -> active tab
3 Contact Us -> active tab & theme

## Screenshots
Screenshot 2023-07-18 143625
Screenshot 2023-07-18 143706
Screenshot 2023-07-18 143737

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by BhartiNagpure** [comment]
@SurajPratap10  as I done with my work please authorized it.

**Comment by SurajPratap10** [comment]
Resolve conflicts @BhartiNagpure

**Comment by BhartiNagpure** [comment]
@SurajPratap10 Resolve conflicts.

**Comment by BhartiNagpure** [comment]
@SurajPratap10 what type of conflicts are shown

**Comment by BhartiNagpure** [comment]
@SurajPratap10  resolve conflicts please review it.

**Comment by BhartiNagpure** [comment]
@SurajPratap10 resolve .

**Comment by SurajPratap10** [comment]
image

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
