### PR TITLE
Responsive About Page

### LINKED ISSUE #564: Contact page not responsive and aligned properly
**Describe the bug**
About us page is not properly aligned and responsive 

**To Reproduce**
Changes need to be done in styles

**Expected behavior**
A constant and flexible layout and alignment should be maintained 

**Screenshots**
![Uploading Screenshot_2023-07-10-00-30-41-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg …]

**Smartphone (please complete the following information):**

- Device: Realme
- OS: Android 
- Browser Chrome 

I would like to ok implement proper alignment and layout for about page for all screen sizes.

Please assign me this issue under gssoc23 label

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Changed styles to make the page responsive.

## Fixes #564 **Contact page not responsive and aligned properly #564**
   closes #564 

## Sample Output

https://github.com/SurajPratap10/Imagine_AI/assets/86224794/eb44fd38-8bc9-42d5-8f44-720118d575fa

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ ] All tests are passing

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@SurajPratap10 can you please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@SurajPratap10 please review this PR!!

**Comment by SurajPratap10** [comment]
Resolve conflicts @AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
@SurajPratap10 resolved all the conflicts

**Comment by AlfiyaSiddique** [comment]
@SurajPratap10 resolve the conflicts again, please review this PR!!

**Comment by SurajPratap10** [comment]
The thing is you have altered so many lines of code no , reason why even if I merge any single PR of other folks it shows conflicts in your PR. Resolve this `conflict` for now and comment quickly. I will merge your PR first 👍and follow the best practices while altering/refactoring the codes in the future..

**Comment by AlfiyaSiddique** [comment]
@SurajPratap Resolved the conflicts.

**Comment by AlfiyaSiddique** [comment]
@SurajPratap10 Done, Resolved the conflicts.

**Review by SurajPratap10 — APPROVED** [review]

**Pull request merged**
