### PR TITLE
ChatBot Fix issue #1269

### PR DESCRIPTION
**Pull request by mansiruhil13**
Chatbot Integration.

Before

Screenshot 2024-10-18 002642

After

Screenshot 2024-10-22 015738

### CODE REVIEW

**Comment by mansiruhil13** [comment]
fix issue #1269

**Review by SurajPratap10 — COMMENTED** [review]
image


NOT FIXED

**Comment by mansiruhil13** [comment]
can you merge? i think, after merge results will come in deployment site? because i have tried , and output comes. eg:
Screenshot 2024-10-22 015738

**Comment by mansiruhil13** [comment]
> A guy fixed it before you so I am closing this PR as I can't merge it now

but i have already created this before.

**Pull request closed without merging**
